### PR TITLE
[INT-191] Support multiple upload targets

### PR DESCRIPTION
**Pull request by balsoft**
We want to try out b2 as out nix cache backend; Therefore, we need to upload to both the old s3 cache and the new b2 one.

### CODE REVIEW

**Comment by notgne2** [comment]
Didn't realize this would end up being the easier method, though I'll leave the review to somebody with more Haskell experience. Did you test this locally first?

**Review by zhenyavinogradov — APPROVED** [review]

**Comment by zhenyavinogradov** [comment]
@balsoft Btw, what to do you think about adding CI for upload-daemon? It would ensure that at least we don't have build-time problems

**Comment by balsoft** [comment]
> Did you test this locally first?

Yes, I did:

```
$ nix run -L . -- -p 1234 -t ssh://x2100-laptop -t ssh://balsoft.ru -j $(nproc) +RTS -N$(nproc) &
[1] 29735
Starting server on localhost:1234 uploading to ["ssh://x2100-laptop","ssh://balsoft.ru"]
$ b hello | nc localhost 1234
Queued /nix/store/yb5q57zxv6hgqql42d5r8b5k5mcq6kay-hello-2.10
Queued 1 paths
Uploaded /nix/store/yb5q57zxv6hgqql42d5r8b5k5mcq6kay-hello-2.10 to ssh://balsoft.ru
Uploaded /nix/store/yb5q57zxv6hgqql42d5r8b5k5mcq6kay-hello-2.10 to ssh://x2100-laptop
[balsoft@balsoft.ru:~]$ /nix/store/yb5q57zxv6hgqql42d5r8b5k5mcq6kay-hello-2.10/bin/hello
Hello, world!
[balsoft@X2100-Laptop:~]$ /nix/store/yb5q57zxv6hgqql42d5r8b5k5mcq6kay-hello-2.10/bin/hello
Hello, world!
```

**Comment by balsoft** [comment]
> Btw, what to do you think about adding CI for upload-daemon? It would ensure that at least we don't have build-time problems

Good idea, will do next

**Comment by mkaito** [comment]
How badly would this explode if one of the endpoint hangs indefinitely, an upload fails, or otherwise wonky things happen? Why is this "better" than running multiple instances of the daemon?

**Comment by balsoft** [comment]
> if one of the endpoint hangs indefinitely

`nix copy` has a timeout. If it does hang indefinitely, this is indeed different compared to running multiple upload-daemons (since we will run out of workers at some point). But I don't think this is really a big issue -- we should just fix `nix copy` if this ever happens. (and in the meantime we can just `systemctl restart upload-daemon` so that the worker pool is refreshed)

> an upload fails

If an upload fails, we will just continue processing new ones as we did before this change.

> otherwise wonky things happen

Define "wonky things".

> Why is this "better" than running multiple instances of the daemon?

First of all, this is cleaner IMO. Instead of having multiple copies of the same service running, with multiple sockets and multiple `nc` calls in the post-build-hook, we just have one service handling multiple stores. But I guess this is subjective.

An objective benefit is that workers are handled more efficiently. If we had two upload-daemons running, we would have to limit the amount of workers for each of them to `$(($(nproc) / 2))` (so that we don't have albali clogged by compression processes). This means any difference in upload/compression speed between stores while we're bottlenecked on workers will lead to unused workers in one upload-daemon while the other one doesn't have enough. With this solution all the free cores will be utilized when there are paths queued.

The only real drawback of this solution as far as I can tell is that it's new, non-battle-tested Haskell code instead of new, non-battle-tested bash/nix.

**Comment by mkaito** [comment]
Not much to battle-test on the nix/bash side. Spin up new instance of code we know works, point at different upload target. Done.

**Pull request merged**
